name: Publish

on:
  release:
    types: [ published ]

jobs:

  publish:
    name: Publish the release version
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository and the branch
        uses: actions/checkout@v3

      - name: Setup the release version and overwrite the existing major version tag
        run: